# Generated by Django 4.1.2 on 2022-10-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SlackUsername', models.CharField(max_length=200)),
                ('Backend', models.BooleanField()),
                ('age', models.IntegerField()),
                ('Bio', models.CharField(max_length=200)),
            ],
        ),
    ]
